export * from './doctor.service';
import { DoctorService } from './doctor.service';
export * from './filter.service';
import { FilterService } from './filter.service';
export * from './patient.service';
import { PatientService } from './patient.service';
export * from './photo.service';
import { PhotoService } from './photo.service';
export * from './receptionist.service';
import { ReceptionistService } from './receptionist.service';
export * from './update.service';
import { UpdateService } from './update.service';
export const APIS = [DoctorService, FilterService, PatientService, PhotoService, ReceptionistService, UpdateService];
